# docker-compose up server

version: "3.8"

services: 
  flask: 
    build:
      context: .
    container_name: flask
    restart: always
    env_file: 
      - .env
    build: .
    ports: 
      - "5000:5000"
    depends_on: 
      - database
    command: sh -c "/wait && flask run --host 0.0.0.0 --reload --debugger"
    
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file: 
      - .env
    volumes: 
      - .data:/data/db
